In [1]:
# Import Libraries

import pandas as pd
import numpy as np

In [3]:
# Load Dataset

df = pd.read_csv("student_data.csv")

df

   Student_ID   Name  Maths  Science  English
0         101   Ravi     85       78       90
1         102  Priya     92       88       95
2         103  Arjun     70       65       72
3         104  Sneha     88       91       84
4         105  Kiran     60       58       65

In [4]:
# Calculate Total Marks

df["Total"] = df["Maths"] + df["Science"] + df["English"]

df

   Student_ID   Name  Maths  Science  English  Total
0         101   Ravi     85       78       90    253
1         102  Priya     92       88       95    275
2         103  Arjun     70       65       72    207
3         104  Sneha     88       91       84    263
4         105  Kiran     60       58       65    183

In [6]:
# Calculate Percentage

df["Percentage"] = (df["Total"] / 300) * 100

df

   Student_ID   Name  Maths  Science  English  Total  Percentage
0         101   Ravi     85       78       90    253   84.333333
1         102  Priya     92       88       95    275   91.666667
2         103  Arjun     70       65       72    207   69.000000
3         104  Sneha     88       91       84    263   87.666667
4         105  Kiran     60       58       65    183   61.000000

In [7]:
# Grade Calculation

def grade(percent):
    if percent >= 90:
        return "A+"
    elif percent >= 80:
        return "A"
    elif percent >= 70:
        return "B"
    elif percent >= 60:
        return "C"
    else:
        return "Fail"

df["Grade"] = df["Percentage"].apply(grade)

df

   Student_ID   Name  Maths  Science  English  Total  Percentage Grade
0         101   Ravi     85       78       90    253   84.333333     A
1         102  Priya     92       88       95    275   91.666667    A+
2         103  Arjun     70       65       72    207   69.000000     C
3         104  Sneha     88       91       84    263   87.666667     A
4         105  Kiran     60       58       65    183   61.000000     C

In [8]:
# Top Performer

top_student = df.loc[df["Percentage"].idxmax()]

print("Top Performer")
print(top_student)

Top Performer
Student_ID          102
Name              Priya
Maths                92
Science              88
English              95
Total               275
Percentage    91.666667
Grade                A+
Name: 1, dtype: object

In [9]:
# Save Report

df.to_csv("student_report.csv", index=False)

print("Report Saved Successfully")

Report Saved Successfully